### ISSUE TITLE
dynamic field throws 'Null check operator used on a null value'

### ISSUE THREAD

**Issue by techouse** [numen31337/copy_with_extension#74] opened 2022-12-28 11:56 UTC
**Describe the issue**

I have a `dynamic` field and the generated code throws a `Null check operator used on a null value` exception.

Possibly a result of https://github.com/numen31337/copy_with_extension/pull/69#issue-1433703875

**Environment details**

`Dart 2.18.6`

**To Reproduce**

Steps to reproduce the behaviour:

Declare a `dynamic` field in a class, i.e. 

```dart
final dynamic action;
```

and the generated code is

```dart
action: action == const $CopyWithPlaceholder() || action == null
        // ignore: unnecessary_non_null_assertion
        ? _value.action!
        // ignore: cast_nullable_to_non_nullable
        : action as dynamic,
```

This will throw an exception when running unit tests

```
Null check operator used on a null value
package:alfred_workflow/src/models/alfred_item.g.dart 211:26         _$AlfredItemCWProxyImpl.call
test/fixtures/models/alfred_item_fixture.dart 93:33                  AlfredItemFactory.uid.<fn>
package:data_fixture_dart/factories/fixture_factory.dart 31:30       FixtureFactory.redefine.<fn>
package:data_fixture_dart/definitions/fixture_definition.dart 24:26  FixtureDefinition.makeMany.<fn>
dart:core                                                            new List.generate
package:data_fixture_dart/definitions/fixture_definition.dart 22:12  FixtureDefinition.makeMany
test/unit/models/alfred_items_test.dart 15:10                        main.<fn>
```

The exception above refers to the line

```dart
? _value.action!
```

where a `null` check operator (`!`) is used on `dynamic`

**Expected behaviour**

No exception and nullability properly handled on a `dynamic` field.

**Additional context**

The only workaround I have found is to use `Object?` instead of `dynamic`, like so:

```dart
final Object? action;
```

and the generated code becomes

```dart
action: action == const $CopyWithPlaceholder()
        ? _value.action
        // ignore: cast_nullable_to_non_nullable
        : action as Object?,
```

You can see the workaround in action [here](https://github.com/techouse/alfred_workflow/blob/master/lib/src/models/alfred_item.g.dart#L209)

**Comment by numen31337** [comment] 2023-02-25 21:08
Hi @techouse,
I attempted to recreate the issue you reported, but I was unable to reproduce the crash you experienced. It's possible that the problem was fixed with the latest version of Dart or that I made a mistake during my testing. Can you take a look at the [following test](https://github.com/numen31337/copy_with_extension/blob/dc9aa4e43e8f075bfb61d21b0c8a24b144914ee9/copy_with_extension_gen/test/gen_nullability_test.dart#L31-L32) and let me know if it addresses the issue you described?

**Comment by techouse** [comment] 2023-02-25 21:31
It does not crash, it just throws all these error messages.

**Comment by numen31337** [comment] 2023-02-25 21:37
@techouse Looks like I'm having difficulty replicating the issue and I am wondering if you can guide me on how to see the relevant error messages.

**Comment by techouse** [comment] 2023-02-26 00:48
@numen31337 of course :) The warning only appears when you actually run the code. In the tests it's muted.

I have created a repo demonstrating it here https://github.com/techouse/copy_with_extension_nullability_issue_demo

Way to reproduce it:

1. clone the repo
2. install the dependencies
3. execute
```bash
dart run bin/main.dart
```

**Comment by numen31337** [comment] 2023-02-26 10:10
For the record, the problem mentioned here is not reflected in https://github.com/numen31337/copy_with_extension/issues/74#issuecomment-1445237437. The https://github.com/numen31337/copy_with_extension/issues/74#issuecomment-1445237437 is representative of the issue #75 which is a different one. This ticket pertains specifically to instances where an object has a dynamic field that was initialised as `null`, and subsequently using `copyWith` on such an object will crash and result in the error message `Null check operator used on a null value` [mentioned earlier](https://github.com/numen31337/copy_with_extension/issues/74#issue-1512721754).

Test case:
```dart
import 'package:copy_with_extension/copy_with_extension.dart';
import 'package:test/test.dart' show test, expect;

part 'gen_nullability_test.g.dart';

@CopyWith()
class TestNullability {
  TestNullability(
    int this.nullableWithNonNullableConstructor,
    this.dynamicField,
    this.integers,
  );

  final int? nullableWithNonNullableConstructor;
  final dynamic dynamicField;
  final List<int> integers;
}

void main() {
  test('TestNullability', () {
    expect(TestNullability(1, null, [1]).copyWith.integers([2]).dynamicField, null);
  });
}
```

Leads to the crash here:
```dart
      dynamicField == const $CopyWithPlaceholder() || dynamicField == null
          // ignore: unnecessary_non_null_assertion
          ? _value.dynamicField! // <--- CRASH
          // ignore: cast_nullable_to_non_nullable
          : dynamicField as dynamic,
```

**Comment by techouse** [comment] 2023-02-26 13:45
@numen31337 correct. My memory on this issue is not the freshest anymore. Let me try to reproduce this in another repo.

**Closed** 2023-02-26 23:11 UTC
Labels: bug
