### ISSUE TITLE
4.0.0, Suggest non-nullable fields can't be assigned to null by `copyWith`

### ISSUE THREAD

**Issue by qiangjindong** [numen31337/copy_with_extension#55] opened 2022-06-13 11:47 UTC
Because the field is now assigned null through copywith, the result is ambiguous: 1. remain unchanged 2. set to null.

**Comment by numen31337** [comment] 2022-08-04 21:07
Do you have suggestions on how can we possibly inform the end user about it? Unfortunately, I'm out of idea here 🤷‍♂️.

**Comment by llfbandit** [comment] 2023-07-06 15:16
I think the code generated is close to allow this:

The generator could output a slightly changed definition.

`_$FooCWProxy` definition is correct and totally fine to achieve the goal.
I guess there's nothing to change to `_$FooCWProxyImpl`.

```dart
@CopyWith()
class Foo {
  const Foo({
    required int nonnull,
    int? nullable,
  });

  final int nonnull;
  final int? nullable;
}

abstract class _$FooCWProxy {
  Foo call({
    int nonnull,
    int? nullable,
  });
}
```

**Comment by myxzlpltk** [comment] 2023-09-24 10:56
if it non null, dart will force you to use `required` keyword in implementation class

**Comment by tolotrasamuel** [comment] 2024-06-15 19:25
Any update on this ?

**Comment by tolotrasamuel** [comment] 2024-06-15 19:31
```
import 'package:app_core/model/app/base_model/updatable_entity.dart';
import 'package:app_core/model/app/custom/income.model.dart';
import 'package:app_core/repository_helper/json_map.dart';
import 'package:app_core/utils/annotations/annotations.dart';
import 'package:copy_with_extension/copy_with_extension.dart';

part 'income.g.dart';

enum IncomeType {
  adReward,
  couponCode,
  refill,
}

@myJsonSerializable
@CopyWith()
class Income {
  final int value;
  final IncomeType type;
  final String incomeSourceId;

  Income({
    required this.incomeSourceId,
    required this.type,
    required this.value,
  });

  factory Income.fromJson(JsonMap json) => _$IncomeFromJson(json);

  JsonMap toJson() => _$IncomeToJson(this);

  factory Income.empty() => Income(
        incomeSourceId: "someID"
        value: 0,
        type: IncomeType.adReward,
      );

}

void main(){
  final someApiResult = null;
  final a = Income.empty().copyWith(value: someApiResult); // not null safe here
  print(a.value);
}

```

Could you please fix this? The problem is copyWith function parameters is not null safe. The compiler does not report the bug illustrated above. Normally, the developer forgot to write step that handle an edge case were the `apiResult` is null. 

This will leads to unwanted behaviour at runtime. I checked the code. This seems like an easy fix:

Instead of generating code:  

```
 Income call({
    String? incomeSourceId,
    IncomeType? type,
    int? value,
  });
```

Can you generate: 

```
 Income call({
    String incomeSourceId,
    IncomeType type,
    int value,
  });
```

**Comment by numen31337** [comment] 2024-11-30 13:19
With this approach, the behavior would differ from the one used by the official Flutter libraries, for instance, [here](https://api.flutter.dev/flutter/material/ThemeData/copyWith.html). However, it feels like the right thing to do. I would personally assume that Flutter employs the approach of passing `null` because of the significant amount of code and readability that would be compromised if it were done otherwise. Nevertheless, this is not an issue with generated code.

After modifying the behavior, I did not observe any side effects. Of course, it is a breaking change for existing users, so it will be released as a major update.

**Closed** 2024-11-30 15:01 UTC
Labels: question
